// Please read the @/lib/types/toolconfig file for more details on each field.
import { ToolConfig } from '@/lib/types/toolconfig'

export const toolConfig: ToolConfig = {
  ////// Base config
  company: {
    name: 'プロフィール検索',
    theme: 'default',
    homeUrl: '/dashboard',
    appUrl: '/dashboard',
    description: 'Linked',
    logo: 'https://cdn2.iconfinder.com/data/icons/privacy-policy/512/privacy-data-policy-security-05-512.png',
    navbarLinks: [
      { label: 'App', href: `/dashboard` },
      { label: 'Home', href: '/' },
    ],
  },
  ////// SEO stuff
  metadata: {
    title: 'Linked',
    description: 'Linked',
    og_image: 'https://linked.spaceai.jp/og.png',
    canonical: 'https://linked.spaceai.jp/dashboard',
  },

  ////// Paywall
  paywall: true,
  credits: 5,

  ////// Location
  toolPath: '/dashboard',

  ////// AI config
  aiModel: '',
  systemMessage: '',

  ////// Form input
  type: 'groq',
  fields: [
    {
      label: 'アカウントID',
      name: 'account_id',
      type: 'input',
      inputType: 'string',
      placeholder: '',
      required: true,
      custom: true,
      // validation: yup.string().required('Account ID is required'),
    },
    {
      label: 'ワークフロー名',
      name: 'name',
      type: 'input',
      placeholder: '',
      required: true,
      // validation: yup.string().required('ワークフロー名は必須です'),
    },
    {
      label: '処理',
      name: 'type',
      type: 'checkbox',
      options: [
        { label: '検索', value: '0' },
        { label: 'つながり申請', value: '1' },
      ],
      required: true,
      initialValue: '0',
      custom: true,
    },
    {
      label: 'Active Tab',
      name: 'active_tab',
      type: 'input',
      inputType: 'string',
      required: false,
      custom: true,
    },
    {
      label: '対象カラム名',
      name: 'extract_column',
      type: 'input',
      inputType: 'string',
      required: false,
      custom: true,
    },
    {
      label: 'URL',
      name: 'search_url',
      type: 'input',
      placeholder: '',
      required: false,
      custom: true,
    },
    {
      label: 'target public identifiers',
      name: 'target_public_identifiers',
      type: 'input',
      placeholder: '',
      required: false,
      custom: true,
    },
    {
      label: 'lead_list id',
      name: 'target_workflow_id',
      type: 'input',
      placeholder: '',
      required: false,
      custom: true,
    },
    {
      label: 'キーワード',
      name: 'keywords',
      type: 'input',
      placeholder: '',
      required: false,
      custom: true,
    },
    {
      label: '企業URL',
      name: 'company_urls',
      type: 'input',
      placeholder: '',
      required: false,
      custom: true,
    },
    {
      label: 'つながり',
      name: 'network_distance',
      type: 'checkbox',
      options: [
        { label: '1次', value: '1' },
        { label: '2次', value: '2' },
        { label: '3次', value: '3' },
      ],
      required: false,
      multiple: true,
      custom: true,
    },
    {
      label: '1回毎の対象数',
      name: 'limit_count',
      type: 'input',
      inputType: 'number',
      placeholder: '20',
      initialValue: '20',
      required: false,
      max: 200,
      min: 1,
      // validation: yup.number().required('検索数は必須です'),
    },
    {
      label: '時間(JST)',
      name: 'scheduled_hours',
      type: 'checkbox',
      options: [
        { label: '0', value: '0' },
        { label: '1', value: '1' },
        { label: '2', value: '2' },
        { label: '3', value: '3' },
        { label: '4', value: '4' },
        { label: '5', value: '5' },
        { label: '6', value: '6' },
        { label: '7', value: '7' },
        { label: '8', value: '8' },
        { label: '9', value: '9' },
        { label: '10', value: '10' },
        { label: '11', value: '11' },
        { label: '12', value: '12' },
        { label: '13', value: '13' },
        { label: '14', value: '14' },
        { label: '15', value: '15' },
        { label: '16', value: '16' },
        { label: '17', value: '17' },
        { label: '18', value: '18' },
        { label: '19', value: '19' },
        { label: '20', value: '20' },
        { label: '21', value: '21' },
        { label: '22', value: '22' },
        { label: '23', value: '23' },
      ],
      required: false,
    },
    // {
    //   label: '日(JST)',
    //   name: 'scheduled_days',
    //   type: 'checkbox',
    //   options: [
    //     { label: '1', value: '1' },
    //     { label: '2', value: '2' },
    //     { label: '3', value: '3' },
    //     { label: '4', value: '4' },
    //     { label: '5', value: '5' },
    //     { label: '6', value: '6' },
    //     { label: '7', value: '7' },
    //     { label: '8', value: '8' },
    //     { label: '9', value: '9' },
    //     { label: '10', value: '10' },
    //     { label: '11', value: '11' },
    //     { label: '12', value: '12' },
    //     { label: '13', value: '13' },
    //     { label: '14', value: '14' },
    //     { label: '15', value: '15' },
    //     { label: '16', value: '16' },
    //     { label: '17', value: '17' },
    //     { label: '18', value: '18' },
    //     { label: '19', value: '19' },
    //     { label: '20', value: '20' },
    //     { label: '21', value: '21' },
    //     { label: '22', value: '22' },
    //     { label: '23', value: '23' },
    //     { label: '24', value: '24' },
    //     { label: '25', value: '25' },
    //     { label: '26', value: '26' },
    //     { label: '27', value: '27' },
    //     { label: '28', value: '28' },
    //     { label: '29', value: '29' },
    //     { label: '30', value: '30' },
    //     { label: '31', value: '31' },
    //   ],
    //   required: false,
    // },
    {
      label: '曜日(JST)',
      name: 'scheduled_weekdays',
      type: 'checkbox',
      options: [
        { label: '日', value: '0' },
        { label: '月', value: '1' },
        { label: '火', value: '2' },
        { label: '水', value: '3' },
        { label: '木', value: '4' },
        { label: '金', value: '5' },
        { label: '土', value: '6' },
      ],
      required: false,
    },
  ],
  submitText: '実行',
  submitTextGenerating: '実行中',
  responseTitle: '処理が完了しました',
  responseSubTitle: '',

  ////// UI config
  navbarLanding: {
    bgColor: 'primary',
    textColor: 'text-neutral',
    buttonColor: 'accent',
  },

  navbarApp: {
    bgColor: 'base-100',
    textColor: 'text-base-content',
    buttonColor: 'accent',
  },

  footerLanding: {
    bgColor: 'accent',
    textColor: 'white',
  },

  footerApp: {
    bgColor: 'accent',
    textColor: 'white',
  },
}
