export interface App {
  href: string
  title: string
  shortTitle: string
  shortDesc: string
  tags: string[]
  features: string[]
  useCases: string[]
  techStack: string[]
  image: string
  simpleFeatures: string[]
}

export const apps = [
  {
    href: '/apps/chat',
    title: 'Advanced AI Chat Assistant',
    shortTitle: 'AI Chat',
    shortDesc: 'Intelligent conversational AI with advanced capabilities',
    tags: ['OpenAI', 'Claude', 'LLaMA 3', 'Groq', 'DeepSeek', 'Multi-Modal'],
    features: [
      'Multiple AI model support (GPT-4o, Claude 3.5 Sonnet, LLaMA 3, xAI, DeepSeek)',
      'Multi-modal capabilities (image input)',
      'Real-time web search integration',
      'Document generation and editing',
      'Tool integration',
      'Generative UI',
    ],
    useCases: [
      'Personal AI assistant',
      'Research and analysis',
      'Content creation',
      'Document processing',
      'Web search assistance',
      'Multi-modal interactions',
      'Tool-augmented conversations',
      'Knowledge base creation',
    ],
    techStack: [
      'Next.js 14',
      'React',
      'TypeScript',
      'Supabase',
      'Tailwind CSS',
      'shadcn/ui',
      'Vercel AI SDK',
      'OpenAI',
      'Anthropic',
      'Groq',
      'xAI',
      'DeepSeek',
      'Cloudflare R2 Storage',
      'Serper API for web search',
      'Jina AI for content extraction',
      'Generative UI',
    ],
    image:
      'https://images.unsplash.com/photo-1692607334850-4a3ede6ec657?q=80&w=3027&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    simpleFeatures: [
      'Use different AI models like GPT-4 and Claude in one place',
      'Upload and analyze images with AI',
      'Search the internet in real-time while chatting',
      'Create and edit documents right in the chat',
    ],
  },
  {
    href: '/apps/pdf',
    title: 'Chat with a PDF ',
    shortTitle: 'PDF Chat',
    shortDesc: 'Upload and chat with PDFs',
    tags: ['OpenAI', 'GPT-4o (mini)', 'PDF Processing', 'Vector Search'],
    features: [
      'PDF text extraction',
      'Vector embeddings generation',
      'RAG search',
      'Semantic search',
      'Context-aware responses',
      'Document history',
    ],
    useCases: [
      'Document analysis',
      'Research assistance',
      'Legal document review',
      'Educational material study',
      'Technical documentation search',
      'Knowledge base creation',
    ],
    techStack: [
      'Next.js 14',
      'React',
      'TypeScript',
      'Supabase',
      'Tailwind CSS',
      'LangChain',
      'shadcn/ui',
      'OpenAI Embeddings',
      'RAG',
      'Supabase Vector Store',
      'pdf-parse',
      'LangChain',
      'Cloudflare R2',
    ],
    image:
      'https://images.unsplash.com/photo-1638787377553-0547687f3a87?q=80&w=2872&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    simpleFeatures: [
      'Upload any PDF and chat with its contents',
      'Ask questions about specific parts of the document',
      'Get smart summaries of long documents',
      'Save and access your document history anytime',
    ],
  },
  {
    href: '/apps/audio/app',
    title: 'Speech to text using Whisper',
    shortTitle: 'Whisper',
    shortDesc: 'Audio transcription & summarization',
    tags: ['Whisper', 'LLaMA 3', 'Audio Processing', 'Transcription'],
    features: [
      'Multi-language support',
      'Real-time transcription',
      'Audio summarization',
      'Speaker diarization',
      'Timestamp generation',
      'Custom vocabulary',
    ],
    useCases: [
      'Meeting transcription',
      'Podcast processing',
      'Interview analysis',
      'Lecture notes',
      'Accessibility tools',
      'Content localization',
    ],
    techStack: [
      'Next.js 14',
      'React',
      'TypeScript',
      'Supabase',
      'Tailwind CSS',
      'shadcn/ui',
      'Whisper API',
      'LLaMA 3.1',
      'Cloudflare R2',
      'Groq',
      'Replicate',
    ],
    image:
      'https://images.unsplash.com/photo-1492879291357-620e858bd26a?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    simpleFeatures: [
      'Convert speech to text in many languages',
      'Get text versions of audio files instantly',
      'Identify different speakers in conversations',
      'Create summaries of audio content',
    ],
  },
  {
    href: '/apps/voice',
    title: 'Text to lifelike speech',
    shortTitle: 'ElevenLabs TTS',
    shortDesc: 'Advanced text-to-speech synthesis',
    tags: ['Elevenlabs', 'Text to Speech', 'Audio Generation'],
    features: [
      '26+ languages support',
      '1000+ voice options',
      'Custom voice cloning',
      'Real-time streaming',
      'Voice emotion control',
      'Speech rate adjustment',
    ],
    useCases: [
      'Audiobook creation',
      'Video narration',
      'Accessibility tools',
      'Language learning',
      'Virtual assistants',
      'Content localization',
    ],
    techStack: [
      'Next.js 14',
      'React',
      'TypeScript',
      'Supabase',
      'Tailwind CSS',
      'shadcn/ui',
      'ElevenLabs API',
      'MediaRecorder API',
      'Cloudflare R2',
    ],
    image:
      'https://images.unsplash.com/photo-1666868291591-9f8e0353c9ce?q=80&w=3027&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    simpleFeatures: [
      'Turn text into natural-sounding speech',
      'Choose from over 1000 different voices',
      'Create your own custom AI voice',
      'Support for 26+ languages',
    ],
  },
  {
    href: '/apps/gpt/app',
    title: 'Structured output with GPT-4o',
    shortTitle: 'GPT 4o',
    shortDesc: 'Generate structured output (JSON or text) with GPT',
    tags: ['OpenAI', 'GPT-4o (mini)'],
    features: [
      'Structured output generation',
      'JSON/text formatting',
      'JSON schema validation',
      'Custom prompt templates',
      'Real-time streaming',
      'Function calling support',
    ],
    useCases: [
      'Content generation',
      'Data structuring',
      'API response formatting',
      'Documentation',
      'Text analysis',
      'Format conversion',
      'Business logic',
      'Code generation',
      'Text generation',
      'Structured output generation',
    ],
    techStack: [
      'Next.js 14',
      'React',
      'TypeScript',
      'Supabase',
      'Tailwind CSS',
      'OpenAI API',
      'LangChain',
      'shadcn/ui',
      'Vercel AI SDK',
    ],
    image:
      'https://images.unsplash.com/photo-1553933899-131780ba04a3?q=80&w=2786&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    simpleFeatures: [
      'Get AI responses in specific formats (like JSON)',
      'Validate data structure automatically',
      'Create custom templates for repeated tasks',
      'Stream responses in real-time',
    ],
  },

  {
    href: '/apps/vision/app',
    title: 'See with GPT-4o',
    shortTitle: 'GPT-4o Vision',
    shortDesc: 'AI-powered image analysis',
    tags: ['OpenAI', 'GPT-4o', 'Computer Vision', 'Image Analysis'],
    features: [
      'Multi-image analysis',
      'Detailed scene description',
      'Object detection',
      'Text extraction from images',
      'Visual question answering',
      'Image content moderation',
    ],
    useCases: [
      'Content moderation',
      'Accessibility services',
      'E-commerce product analysis',
      'Medical image interpretation',
      'Document processing',
      'Visual search systems',
    ],
    techStack: [
      'Next.js 14',
      'React',
      'TypeScript',
      'Supabase',
      'Tailwind CSS',
      'shadcn/ui',
      'OpenAI Vision API',
      'Cloudflare R2',
      'LangChain',
    ],
    image:
      'https://images.unsplash.com/photo-1696517170961-661e9dca962e?q=80&w=2960&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    simpleFeatures: [
      'Analyze multiple images at once',
      'Get detailed descriptions of any image',
      'Extract text from images',
      "Ask questions about what's in images",
    ],
  },
  {
    href: '/apps/sdxl/app',
    title: 'Images with SDXL',
    shortTitle: 'SDXL',
    shortDesc: 'High-quality AI image generation',
    tags: ['Replicate', 'SDXL', 'Image Generation', 'Stable Diffusion'],
    features: [
      'Text-to-image generation',
      'High-resolution output',
      'Style customization',
      'Batch generation',
      'Image variations',
    ],
    useCases: [
      'Image generation',
      'Brand assets',
      'Social media content',
      'Presentation images',
      'Digital art creation',
      'Product visualization',
      'Marketing materials',
      'Concept art',
      'UI/UX mockups',
    ],
    techStack: [
      'Next.js 14',
      'React',
      'TypeScript',
      'Supabase',
      'Tailwind CSS',
      'shadcn/ui',
      'Replicate API',
      'Cloudflare R2',
      'Sharp',
    ],
    image:
      'https://images.unsplash.com/photo-1717501218385-55bc3a95be94?q=80&w=2832&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    simpleFeatures: [
      'Create high-quality images from text descriptions',
      'Generate multiple images at once',
      'Customize image styles and looks',
      'Create variations of existing images',
    ],
  },
  {
    href: '/apps/dalle/app',
    title: 'Images with DALL·E',
    shortTitle: 'DALL·E',
    shortDesc: 'AI-powered image generation',
    tags: ['OpenAI', 'DALL·E 3', 'Image Generation'],
    features: [
      'Text-to-image generation',
      'High-resolution output',
      'Style customization',
      'Batch generation',
      'Image variations',
    ],
    useCases: [
      'Image generation',
      'Brand assets',
      'Social media content',
      'Presentation images',
      'Digital art creation',
      'Product visualization',
      'Marketing materials',
      'Concept art',
      'UI/UX mockups',
    ],
    techStack: [
      'Next.js 14',
      'React',
      'TypeScript',
      'Supabase',
      'Tailwind CSS',
      'shadcn/ui',
      'OpenAI API',
      'Cloudflare R2',
    ],
    image:
      'https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?q=80&w=2874&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    simpleFeatures: [
      'Create images from text descriptions',
      'Generate professional-quality artwork',
      'Make multiple versions of the same idea',
      'Control the style and look of generated images',
    ],
  },
  {
    href: '/apps/llama/app',
    title: 'JSON or text with LLaMA 3',
    shortTitle: 'LLaMA 3',
    shortDesc: 'Structured data generation with LLaMA',
    tags: ['Groq', 'LLaMA 3', 'JSON', 'Text Generation'],
    features: [
      'Fast inference speed',
      'Structured output generation',
      'JSON/text formatting',
      'JSON schema validation',
      'Custom prompt templates',
      'Real-time streaming',
      'Function calling support',
    ],
    useCases: [
      'Content generation',
      'Data structuring',
      'API response formatting',
      'Documentation',
      'Text analysis',
      'Format conversion',
      'Business logic',
      'Code generation',
      'Text generation',
      'Structured output generation',
    ],
    techStack: [
      'Next.js 14',
      'React',
      'TypeScript',
      'Supabase',
      'Tailwind CSS',
      'shadcn/ui',
      'Groq API',
      'LangChain',
      'Cloudflare R2',
    ],
    image:
      'https://images.unsplash.com/photo-1674027444485-cec3da58eef4?q=80&w=2832&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    simpleFeatures: [
      'Get super-fast AI responses',
      'Create structured data (like JSON) easily',
      'Use custom templates for consistent results',
      "Stream responses as they're being generated",
    ],
  },
  {
    href: '/apps/claude',
    title: 'JSON or text with Claude 3',
    shortTitle: 'Claude 3.5 Sonnet',
    shortDesc: 'AI-powered business planning',
    tags: ['Anthropic', 'Claude 3', 'JSON', 'Business Planning'],
    features: [
      'Structured output generation',
      'JSON/text formatting',
      'JSON schema validation',
      'Custom prompt templates',
      'Real-time streaming',
      'Function calling support',
    ],
    useCases: [
      'Content generation',
      'Data structuring',
      'API response formatting',
      'Documentation',
      'Text analysis',
      'Format conversion',
      'Business logic',
      'Code generation',
      'Text generation',
      'Structured output generation',
    ],
    techStack: [
      'Next.js 14',
      'React',
      'TypeScript',
      'Supabase',
      'Tailwind CSS',
      'Anthropic API',
      'shadcn/ui',
      'LangChain',
    ],
    image:
      'https://images.unsplash.com/photo-1717501217986-f2c4842edfd7?q=80&w=2832&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    simpleFeatures: [
      'Get highly accurate structured responses',
      'Create formatted data (JSON or text)',
      'Use templates for consistent outputs',
      'Get responses that follow exact rules',
    ],
  },
  {
    href: '/apps/grok',
    title: 'JSON or text with xAI Grok',
    shortTitle: 'Grok',
    shortDesc: 'AI-powered Product Hunt launch simulation',
    tags: ['xAI', 'Grok', 'JSON', 'Launch Simulation'],
    features: [
      'Product Hunt launch simulation',
      'Structured output generation',
      'JSON/text formatting',
      'Metrics prediction',
      'Community interaction simulation',
      'Launch strategy analysis',
      'xAI Grok API SDK',
    ],
    useCases: [
      'Product launch planning',
      'Market validation',
      'Community engagement simulation',
      'Launch metrics prediction',
      'Strategy optimization',
      'Launch timing analysis',
      'Content generation',
      'Structured output generation',
    ],
    techStack: [
      'Next.js 14',
      'React',
      'TypeScript',
      'Supabase',
      'Tailwind CSS',
      'shadcn/ui',
      'Vercel AI SDK',
      'xAI Grok API',
    ],
    image:
      'https://images.unsplash.com/photo-1706081121737-3c3e2d676919?q=80&w=3386&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    simpleFeatures: [
      'Simulate Product Hunt launches with AI',
      'Get predicted metrics and community reactions',
      'Generate structured launch data',
      'Analyze and optimize launch strategies',
    ],
  },
]
