export enum ProviderType {
  LINKEDIN = 0,
}

export enum ProviderStatus {
  CREATION_SUCCESS = 0,
  RECONNECTED = 1,
}

export enum WorkflowType {
  LEAD_LIST = 0, // lead list表示用
  SEARCH = 1,
  INVITE = 2,
  SEND_MESSAGE = 3,
}

export enum ActiveTab {
  SEARCH = 0,
  KEYWORDS = 1,
  LEAD_LIST = 2,
  FILE_URL = 3,
  UPLOAD = 4,
  SEARCH_REACTION = 5,
}

export enum NetworkDistance {
  OUT_OF_NETWORK = 0,
  FIRST_DEGREE = 1,
  SECOND_DEGREE = 2,
  THIRD_DEGREE = 3,
}

export enum WorkflowRunStatus {
  OFF = 0,
  ON = 1,
}
export enum WorkflowStatus {
  FAILED = 0,
  SUCCESS = 1,
}

export enum LeadStatus {
  SEARCHED = 0,
  INVITED_FAILED = 1,
  IN_QUEUE = 10,
  ALREADY_INVITED = 11,
  INVITED = 20,
  ACCEPTED = 30,
  FOLLOW_UP_SENT_FAILED = 31,
  FOLLOW_UP_SENT_IN_QUEUE = 40,
  FOLLOW_UP_SENT = 41,
  REPLIED = 50,
}

export enum ReactionType {
  LIKE = 0,
  COMMENT = 1,
  EMPATHY = 2,
  ENTERTAINMENT = 3,
  INTEREST = 4,
  PRAISE = 5,
  APPRECIATION = 6,
}

export enum MessageTriggerType {
  SEND_TO_ALL = 0,
  SEND_ONLY_IF_THE_LAST_MESSAGE_WAS_FROM_THE_RECIPIENT = 1,
  SEND_ONLY_IF_THE_LAST_MESSAGE_WAS_FROM_ME = 2,
  SEND_ONLY_IF_THE_LAST_MESSAGE_WAS_FROM_THE_RECIPIENT_OR_IF_THERE_IS_NO_MESSAGE_AT_ALL = 3,
  SEND_ONLY_IF_THE_LAST_MESSAGE_WAS_FROM_ME_OR_IF_THERE_IS_NO_MESSAGE_AT_ALL = 4,
  SEND_ONLY_IF_THERE_IS_NO_MESSAGE_AT_ALL = 5,
  SEND_ONLY_IF_THERE_IS_NEVER_BEEN_A_MESSAGE_FROM_THE_RECIPIENT = 6,
}
